#!/usr/bin/perl
use strict;
use warnings;
use utf8;
utf8::is_utf8($_) || utf8::decode($_) for @ARGV;

use FindBin qw($Bin);
use lib $Bin;
use ui_zenity_common;

ui_zenity_sub {
    require HWTAG;

    # get arguments
    my (@etags) = @ARGV;
    die "Not enough arguments" unless @etags;

    my $hwtag = new HWTAG;
    for my $etag (@etags){
        my $basemeta = $hwtag->get_basemeta_from_etag($etag);
        $hwtag->entity_delete($basemeta);
    }
};
